
// ===============================================================================
// 
// This code has been generated by KickStarter :- http://kickstarter.net
// 
// Version :- 2.0.24.14705
// Date    :- 16/09/2003
// Time    :- 14.32
// 
// ===============================================================================
// 
// Copyright (C) 2002 - 2003 KickStarter
// 
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY
// OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT
// LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR
// FITNESS FOR A PARTICULAR PURPOSE.
// 
// ===============================================================================
namespace Appleseed.KickStarter.CommonClasses 
{

	/// <summary>
	///     
	/// </summary>
	public enum Action 
	{
		/// <summary>
		///     
		/// </summary>
		Select, 
		/// <summary>
		///     
		/// </summary>
		Insert,
		/// <summary>
		///     
		/// </summary>
		Update, 
		/// <summary>
		///     
		/// </summary>
		Delete
	}

	/// <summary>
	/// Purpose: Delegate used in RowSelect, RowInsert, RowUpdate and RowDelete Events.
	/// </summary>
	/// <param name="sender" type="object">The object that raised the event.</param>
	/// <param name="e" type="DataChangeEventArgs">The Event Arguments, Contains Action (Select, Insert, Update, Delete).</param>
	public delegate void DataChangeEventHandler(object sender, DataChangeEventArgs e);

	/// <summary>
	///     
	/// </summary>
	/// <remarks>
	///     
	/// </remarks>
	public class DataChangeEventArgs 
	{

		private Action _Action;

        /// <summary>
        /// Gets or sets the action.
        /// </summary>
        /// <value>The action.</value>
        /// <remarks>
        /// </remarks>
		public Action Action 
		{
			get 
			{
				return this._Action;
			}
			set 
			{
				this._Action = value;
			}
		}

        /// <summary>
        /// Initializes a new instance of the <see cref="T:DataChangeEventArgs"/> class.
        /// </summary>
        /// <returns>
        /// A void value...
        /// </returns>
		public DataChangeEventArgs() 
		{
		}

        /// <summary>
        /// Initializes a new instance of the <see cref="T:DataChangeEventArgs"/> class.
        /// </summary>
        /// <param name="action">The action.</param>
        /// <returns>
        /// A void value...
        /// </returns>
		public DataChangeEventArgs(Action action) 
		{
			this.Action = action;
		}
	}
}