//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appleseed.DesktopModules.CoreModules.SignIn {
    
    
    public partial class SignInWithSocialNetwork {
        
        /// <summary>
        /// Signin1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Appleseed.DesktopModules.CoreModules.SignIn.Signin Signin1;
        
        /// <summary>
        /// SocialButtons control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl SocialButtons;
        
        /// <summary>
        /// SocialNetworkButtons1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Appleseed.DesktopModules.CoreModules.SocialNetworksButtons.SocialNetworkButtons SocialNetworkButtons1;
    }
}
