//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace SelfUpdater.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SelfUpdaterEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SelfUpdaterEntities object using the connection string found in the 'SelfUpdaterEntities' section of the application configuration file.
        /// </summary>
        public SelfUpdaterEntities() : base("name=SelfUpdaterEntities", "SelfUpdaterEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SelfUpdaterEntities object.
        /// </summary>
        public SelfUpdaterEntities(string connectionString) : base(connectionString, "SelfUpdaterEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SelfUpdaterEntities object.
        /// </summary>
        public SelfUpdaterEntities(EntityConnection connection) : base(connection, "SelfUpdaterEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SelfUpdatingPackages> SelfUpdatingPackages
        {
            get
            {
                if ((_SelfUpdatingPackages == null))
                {
                    _SelfUpdatingPackages = base.CreateObjectSet<SelfUpdatingPackages>("SelfUpdatingPackages");
                }
                return _SelfUpdatingPackages;
            }
        }
        private ObjectSet<SelfUpdatingPackages> _SelfUpdatingPackages;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SelfUpdatingPackages EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSelfUpdatingPackages(SelfUpdatingPackages selfUpdatingPackages)
        {
            base.AddObject("SelfUpdatingPackages", selfUpdatingPackages);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SelfUpdaterModel", Name="SelfUpdatingPackages")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SelfUpdatingPackages : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SelfUpdatingPackages object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="packageId">Initial value of the PackageId property.</param>
        /// <param name="packageVersion">Initial value of the PackageVersion property.</param>
        /// <param name="source">Initial value of the Source property.</param>
        public static SelfUpdatingPackages CreateSelfUpdatingPackages(global::System.Int32 id, global::System.String packageId, global::System.String packageVersion, global::System.String source)
        {
            SelfUpdatingPackages selfUpdatingPackages = new SelfUpdatingPackages();
            selfUpdatingPackages.Id = id;
            selfUpdatingPackages.PackageId = packageId;
            selfUpdatingPackages.PackageVersion = packageVersion;
            selfUpdatingPackages.Source = source;
            return selfUpdatingPackages;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PackageId
        {
            get
            {
                return _PackageId;
            }
            set
            {
                OnPackageIdChanging(value);
                ReportPropertyChanging("PackageId");
                _PackageId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PackageId");
                OnPackageIdChanged();
            }
        }
        private global::System.String _PackageId;
        partial void OnPackageIdChanging(global::System.String value);
        partial void OnPackageIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PackageVersion
        {
            get
            {
                return _PackageVersion;
            }
            set
            {
                OnPackageVersionChanging(value);
                ReportPropertyChanging("PackageVersion");
                _PackageVersion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PackageVersion");
                OnPackageVersionChanged();
            }
        }
        private global::System.String _PackageVersion;
        partial void OnPackageVersionChanging(global::System.String value);
        partial void OnPackageVersionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Source
        {
            get
            {
                return _Source;
            }
            set
            {
                OnSourceChanging(value);
                ReportPropertyChanging("Source");
                _Source = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Source");
                OnSourceChanged();
            }
        }
        private global::System.String _Source;
        partial void OnSourceChanging(global::System.String value);
        partial void OnSourceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Install
        {
            get
            {
                return _Install;
            }
            set
            {
                OnInstallChanging(value);
                ReportPropertyChanging("Install");
                _Install = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Install");
                OnInstallChanged();
            }
        }
        private Nullable<global::System.Boolean> _Install;
        partial void OnInstallChanging(Nullable<global::System.Boolean> value);
        partial void OnInstallChanged();

        #endregion

    
    }

    #endregion

    
}
